In [1]:
import numpy as np

In [10]:
arr = np.array([[-1, 2, 0, 4,3],
                [4, -0.5, 6, 0,2],
                [2.6, 0, 7, 8,0],
                [3, -7, 4, 2.0,1]])

In [11]:
print(arr)

[[-1.   2.   0.   4.   3. ]
 [ 4.  -0.5  6.   0.   2. ]
 [ 2.6  0.   7.   8.   0. ]
 [ 3.  -7.   4.   2.   1. ]]


In [27]:
slice = arr[2:4,::3]

In [28]:
print(slice)

[[2.6 8. ]
 [3.  2. ]]


In [30]:
a = np.array([[1,2],
             [3,4]])
b = np.array([[4, 3],
              [2, 1]])

In [31]:
a + 1

array([[2, 3],
       [4, 5]])

In [32]:
b - 2

array([[ 2,  1],
       [ 0, -1]])

In [33]:
a + b

array([[5, 5],
       [5, 5]])

In [34]:
a = a + 1

In [35]:
b = b - 2

In [36]:
a + b


array([[4, 4],
       [4, 4]])

In [37]:
a.sum()

np.int64(14)

In [38]:
a  = a + b

In [39]:
a.sum()

np.int64(16)

In [40]:
x = np.array([1, 2], dtype = np.int64)   
print("\nForcing a Datatype: ")
print(x.dtype)


Forcing a Datatype: 
int64


In [41]:
x = np.array([1, 2])

In [42]:
print(x.dtype)

int64


In [43]:
p = np.array([1, 2])
print(p.dtype)

int64


In [44]:
x = np.array([1, 2], dtype = np.float64)   
print("\nForcing a Datatype: ")
print(x.dtype)


Forcing a Datatype: 
float64
